### ISSUE TITLE
Dont appear any buttom for resolve in the captcha. 

### ISSUE THREAD

**Issue by sergiobetween** [dessant/buster#125]
For Opera 65.0.3467.42, in windows, is not showing the buttom for resolve the captcha.

![image](https://user-images.githubusercontent.com/15216450/69007567-1be6c980-091e-11ea-8b54-e2613e24776b.png)

I have another computer with the same opera and it work. I m not sure what is going on.

**Comment by dessant** [comment]
The "Allow access to search page results" option must be checked for the extension on the chrome://extensions page, otherwise it will not work.

Make sure to read the entire description of the extension, it also contains important details about user input simulation: https://addons.opera.com/en/extensions/details/buster-captcha-solver-for-humans/
