### ISSUE TITLE
Does not work using Brave (Chromium)

### ISSUE THREAD

**Issue by databasetd** [dessant/buster#13]
This extension does not work when using the Brave browser, Brave is Chromium based, and supports all Chrome extensions by default. It seems to be complaining about AudioContext not being allowed to start.

https://imgur.com/a/cv3HWpI

**Comment by dessant** [comment]
The autoplay policy should not affect the extension, and the audio file is decoded successfully despite that warning, though just in case you can disable it by setting chrome://flags/#autoplay-policy to `No user gesture is required` and restarting the browser.

The issue is that in Brave [getChannelData](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer/getChannelData) returns `null`. Try opening a bug report at https://github.com/brave/brave-browser and share this test case with them: https://jsfiddle.net/xpbfgjs4/

```javascript
async function() {
  const rsp = await fetch('https://cors-anywhere.herokuapp.com/https://ccrma.stanford.edu/~jos/mp3/pno-cs.mp3');
  const audio = await rsp.arrayBuffer();

  const ctx = new AudioContext();
  const data = await ctx.decodeAudioData(audio);
  await ctx.close();

  console.log(data.length);
  console.log(data.sampleRate);
  console.log(data.duration);
  console.log(data.numberOfChannels);

  const channelData = data.getChannelData(0)

  console.log(channelData);
  console.log(channelData.length);
}
```

**Comment by databasetd** [comment]
Thanks. I just found out that this may be a problem with Brave's shields causing getChannelData to return null. Disabling Brave's shields made the extension work flawlessly.

**Comment by dessant** [comment]
Thanks for testing! That's unfortunate, they could implement more granular control over fingerprinting protection.
