### ISSUE TITLE
Having trouble using firefox version 55 64 bit Needs a quick fix

### ISSUE THREAD

**Issue by chalitgubkb** [dessant/buster#140]
**System**

* OS name: [Windows 64bit]
* OS version: [10]
* Browser name: [Firefox]
* Browser version: [55]

**Extension**

* Extension version: [0.7.0]

* User input simulation: [no]

* Client app installed successfully: [yes]

**Bug description**

**Logs**

Browser:
```
#Having trouble using firefox version 55 64 bit Needs a quick fix

>>  https://uppic.cc/d/6RCR
I use with firefox version 55 64 bit
The image that I submitted was a problem with firefox version 55 64 bit.
When I clicked on the icon buster the problem occurred.

You can install the browser version from the link below.
>>  https://ftp.mozilla.org/pub/firefox/releases/55.0.3/win64/en-US/
```

Client app:
```
// No
```

**Comment by dessant** [comment]
Please open the browser console as mentioned in the issue template and share the error log.

**Comment by chalitgubkb** [comment]
browser consol >>>     https://uppic.cc/d/6RCp

**Comment by chalitgubkb** [comment]
> Please open the browser console as mentioned in the issue template and share the error log.

All problems showed>>>    https://uppic.cc/d/6RCE

**Comment by dessant** [comment]
Remove the extension and visit https://patrickhlauke.github.io/recaptcha/, then go to the audio challenge and click on the PLAY button. Do you hear any sound?

**Comment by chalitgubkb** [comment]
> Remove the extension and visit https://patrickhlauke.github.io/recaptcha/, then go to the audio challenge and click on the PLAY button. Do you hear any sound?

Yes I still hear

**Comment by dessant** [comment]
> Needs a quick fix
> You can experiment as I suggest in the first place. Yourself Then you will understand

All of this comes after you've nagged me in private messages on Twitter to support Pale Moon, then you've moved on to Firefox 55, and after I've asked you to please use GitHub for bug reports and fill out the issue template with the error log (which you initially didn't do in this thread), you've sent me this message:

> I have successfully reported the problem. Waiting for a fix.

I would suggest that you change your attitude. I've tried the extension with Firefox 55 before I asked and I got an error because the audio couldn't be decoded.

Open source maintainers are not here to be abused and to be told what to do.

After I've spent time talking to you on Twitter and setting up a Windows VM with Firefox 55, I was about to start spending some more time to track down your issue, but you've made it sure with your demanding attitude that I will never look at your issues again.

I will deprecate everything before Firefox ESR 68 in the next few releases.

If the error is present in new browsers, perhaps someone will report it who is able to show some respect.
