### ISSUE TITLE
errors on errors

### ISSUE THREAD

**Issue by ArghKevin** [dessant/buster#172]
for a good bit now(not quite sure how long), when i try to autosolve a recaptcha ive been getting notifs from the extension that say "something went wrong. open the browser console". usually they say there are more than 60 requests per minute for the specified app, but ive seen a few variations. other times, when i click the orange button to autosolve, nothing happens and the icon resets. im on chrome os 81.0.4044.127 and on the chrome browser version of the same name.

**Comment by ArghKevin** [comment]
![image](https://user-images.githubusercontent.com/50538286/81895528-3fa26980-9567-11ea-8fce-165ed43ef059.png)
i now got this when attempting to troubleshoot, not sure if its me or the extension

**Comment by ArghKevin** [comment]
changing my ip got rid of the "try again later" but had no visible effect on autosolving recaptchas

**Comment by ArghKevin** [comment]
![image](https://user-images.githubusercontent.com/50538286/81895722-c6efdd00-9567-11ea-8fe4-649f537daee7.png)
now getting this error when i attempt to solve

**Comment by ArghKevin** [comment]
https://patrickhlauke.github.io/recaptcha/ been using this link for testing/troubleshooting

**Comment by ArghKevin** [comment]
uninstalling and reinstalling changed nothing

**Comment by ArghKevin** [comment]
![image](https://user-images.githubusercontent.com/50538286/81895914-39f95380-9568-11ea-8db7-608cad20b1e6.png)
getting this error again

**Comment by dessant** [comment]
Regarding the automated queries error, see the message above.

Your original error has been fixed in version 0.7.2. The extension was submitted to the Chrome Web Store, but it could take from days to months before it is reviewed by Google.

If you must use Chrome, you could grab the latest release and install it in developer mode until the extension listing is updated on the Chrome Web Store.

Latest release: https://github.com/dessant/buster/releases/tag/v0.7.2

Guide for installation in Chrome: https://stackoverflow.com/a/24577660

The latest version has already been published on Firefox Add-ons.
