### ISSUE TITLE
does not work anymore

### ISSUE THREAD

**Issue by kevin1One** [dessant/buster#185]
**System**

* OS name: [e.g. Windows, Ubuntu]
* OS version: [e.g. 10]
* Browser name: [e.g. Chrome, Firefox]
* Browser version: [e.g. 60]

**Extension**

* Extension version: [e.g. 1.0.0]

* User input simulation: [e.g. yes, no]

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by kevin1One** [comment]
can you say something before closing the issue

**Comment by dessant** [comment]
You have summitted an empty issue template, before editing it out completely. All I can say is that you should put more effort into opening a bug report, otherwise you're wasting the maintainer's time by not being clear about what the exact issue is. A first step would be to check existing issues, because your issue is likely documented already, and if it isn't, then you should do your best to fill out the issue template properly next time.
