### ISSUE TITLE
Firefox: promise.then is not a function

### ISSUE THREAD

**Issue by br4nnigan** [dessant/buster#238]
**System**

* OS name: win
* OS version: 7
* Browser name: Waterfox classic
* Browser version: 2020.09

**Extension**

* Extension version: [e.g. 1.0.0]
1.0.1

**Bug description**

as soon as I hit the solve icon I get a js error:

**Logs**

```
TypeError: calling a builtin Promise constructor without new is forbidden
Error: An unexpected error occurred  script.js:1:66411
Unhandled promise rejection TypeError: promise.then is not a function
Stack trace:
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:369:9
```
Browser:
```
// REPLACE WITH LOGS
```

**Comment by br4nnigan** [comment]
Chromium version works tho

**Comment by dessant** [comment]
Only Waterfox Current is supported. Waterfox Classic has several bugs that prevent the extension from working as expected.

It souldn't have been possible to install version 1.0.1 from AMO in Waterfox Classic, because the minimum supported version is Firefox 68, and since Classic is based on Firefox 56, the browser should have refused the installation attempt. Did you install the extension from AMO?

You could try this workaround, but I don't know if it will help: https://github.com/dessant/buster/issues/141

**Comment by br4nnigan** [comment]
No, I just downloaded the zip from github. Alright I understand that. At least you tried to make Waterfox work which is super cool by you.
