### ISSUE TITLE
NextDNS sources to allow list

### ISSUE THREAD

**Issue by SuicideVillan** [dessant/buster#266]
**System**

* OS name: OSX
* OS version: Catalina 10.15.6
* Browser name: Chrome
* Browser version: 87.0.4280.141

**Bug description**

Cant use with nextDNS and some blocklists.  What sources I should allow on nextDNS?

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
If you're using the default speech service, the extension can connect to these hosts:

www.google.com
www.recaptcha.net
api.wit.ai (CNAME points to wit-edge.c10r.facebook.com)

There have been reports about the Wit.ai host being blocked by tracking protection in some browsers, so that's the most likely culprit, if you're experiencing issues.
