### ISSUE TITLE
Potential stolen extension on the Firefox store.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [dessant/buster#268]
I´ve noticed upon checking the Firefox extension store that an another Buster extension was present, this one had no announced edits or modifications according to the description, and used your repo as their homepage for the stolen buster.
After downloading their .fxi and comparing it with yours with a quick diff, it seems, outside of the META_INF containing the Mozilla signing keys, that nothing has been tempered with yet, with only the manifest.json differing from your extension with the different naming scheme.
Until a confirmation that this was indeed stolen, I´ve reported the following extension copy.
Note that this user has stolen Universal Bypass too with it seems, just a name edit on the Firefox extension store. I´ll post an issue to their repo too.

https://addons.mozilla.org/en-US/firefox/addon/buster-captcha-resolver/

**Comment by dessant** [comment]
Thanks for letting me know! It appears to be also a case of impersonation, because there is a contribution page in the extension, so the developer is practically requesting donations for me, in my name. Please report them to amo-admins@mozilla.com, reports submitted through the AMO form are sometimes forgotten.

Here are other ways to contact Mozilla employees: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us
