### ISSUE TITLE
List of publicly available Speech to Text API keys

### ISSUE THREAD

**Issue by Gitoffthelawn** [dessant/buster#274]
Recently the 'Wit Speech API (managed)' option in Buster stopped working for me.  It always fails.  A quick question: What does "managed" mean for that selection?

All the other APIs seem to require keys.  I really prefer not to create a Facebook, Google, or Microsoft account, and I tried 5 times to create an IBM Cloud account, and their site failed each time.

That got me thinking... most users of Buster probably only use their Speech to Text API keys for Buster, and therefore probably only use the API a couple times each day.  Everyone spending time getting their own API key seems like overkill and a collective waste of time and energy.  It would be great to have a place for people to share their API keys, if they are willing and it's not violating any laws or anything.

Alternatively, if steps could be published that really work to quickly get an API key without giving the big data collection companies your info, that would be nice too.  (I tried the "give them an email from a temporary email service" technique and I didn't have success.)

**Comment by dessant** [comment]
The default speech recognition service is `Wit Speech API (managed)`, which means that the API keys are set up and managed by me, so that users don't have to sign up for Facebook and Wit.ai to use the extension.

You can get similar API keys by following this guide: https://github.com/dessant/buster/wiki/Configuring-Wit.ai

I think IBM Watson asks for relatively minimal data, but I don't remember the details: https://www.ibm.com/cloud/watson-speech-to-text

It would be problematic to begin pooling API keys from random users. With the exception of Wit.ai, these services have a small free tier, and sometimes a credit card must be provided to use it, so people could face charges by sharing their API keys.

Spammers would also latch onto these API keys to use them, and deplete their quota.

**Comment by Gitoffthelawn** [comment]
Since AFAIK Wit and Watson are both free, what about some of us just voluntarily submitting some keys to add to the list of managed keys?

It seems like if you use your own Wit API key, it is trivial for Facebook to track you, but as a community, we can likely make such tracking meaningless for Facebook.
