### ISSUE TITLE
Error: AudioContext is not defined

### ISSUE THREAD

**Issue by normanlol** [dessant/buster#277]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Librewolf (fork of Firefox)
* Browser version: v87.0-3 

**Extension**

* Extension version: 1.1.1

* User input simulation: yes

* Client app version: 0.3.0
* Client app installed successfully: yes

**Bug description**
Using Librewolf, go to any Captcha and try to user the simulation feature provided by the client. 

I assume Librewolf is supported because it is just a fork of Firefox but I may be wrong.

Example: https://streamable.com/ihdoep

**Logs**
Browser:
```
Error: AudioContext is not defined
```

Client app:
```
2021/04/02 19:55:25.047457 Starting client (version: 0.3.0)
2021/04/02 19:55:25.047457 Receiving message
2021/04/02 19:55:25.047457 Processing message
2021/04/02 19:55:25.047457 Command: ping
2021/04/02 19:55:25.047457 Sending response
2021/04/02 19:55:25.048458 Receiving message
2021/04/02 19:55:25.126475 Processing message
2021/04/02 19:55:25.126475 Command: moveMouse
2021/04/02 19:55:25.126475 X: -48, Y: 1
2021/04/02 19:55:25.256503 Sending response
2021/04/02 19:55:25.256503 Receiving message
2021/04/02 19:55:25.364531 Processing message
2021/04/02 19:55:25.364531 Command: clickMouse
2021/04/02 19:55:25.393534 Sending response
2021/04/02 19:55:25.393534 Receiving message
```

**Comment by dessant** [comment]
The Web Audio API seems to be disabled in your browser, if AudioContext is not defined.

**Comment by dessant** [comment]
Librewolf has disabled the API using the `dom.webaudio.enabled` config option. You could try enabling it back and testing the extension again after restarting the browser.

https://gitlab.com/librewolf-community/settings/-/blob/master/librewolf.cfg#L1896

**Comment by dessant** [comment]
Your video also shows the mouse moving to the wrong position, because `privacy.resistFingerprinting` is enabled, and you most likely use a HDPI display, but the extension does not know your real screen resolution to correctly determine where to move the mouse.

The solution is to either disable `privacy.resistFingerprinting` from about:config, or also enable keyboard navigation from the extension's options. The extension will not rely on screen coordinates when navigation is done with keyboard events.
