### ISSUE TITLE
Donation popup

### ISSUE THREAD

**Issue by panos4tw** [dessant/buster#293]
If we make a donation, does the donation popup at 30/100 iteration stops ...popping up? Any way to avoid it?

**Comment by dessant** [comment]
There is not, because there is no need to, a user will only see the popup on the 30th and 100th use during the lifetime of the extension, unless they have installed the extension again in a fresh profile. The fact that this is a problem for you points to your use of automation. Please don't abuse this extension, it is not meant to be used in an automated way.
