### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by Milo123459** [dessant/buster#347]
**System**

* OS name: Windows
* OS version: 11
* Browser name: Chrome
* Browser version: 100

**Extension**

* Extension version: 1.3.1

* User input simulation: Yes (not sure how to check)

**Bug description**

I went [here](https://www.google.com/recaptcha/api2/demo) and clicked the buster icon, only to find that nothing happened.

**Logs**

No logs

**Comment by dessant** [comment]
Please share a screenshot of the extension's options page. Which icon are you clicking, the one in the browser toolbar or the one in the reCAPTCHA popup? You should also update your browser.

**Comment by Milo123459** [comment]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/50248166/168623297-e2521184-4110-4e38-b04b-c6050988b858.png">

This is the options page, and I'm clicking the icon on the pop-up. I have also updated my browser.

**Comment by dessant** [comment]
Does the button begin to animate when you click it, but nothing else happens? Are you trying to click the button with a script?

**Comment by Milo123459** [comment]
It does begin to animate.

**Comment by dessant** [comment]
So in fact something actually does happen. :grinning:

**Comment by Milo123459** [comment]
But it doesn't solve the captcha? I tried clicking verify straight afterwords and it told me to enter some text.

**Comment by dessant** [comment]
Yes, there is probably an issue, I was just trying to point out that you have [repeatedly](https://github.com/dessant/buster/issues/346) left out details from your bug report, and that makes it very hard to find out what the issue is, because the extension works on my end. Maybe there is an error in a log, but who knows if you've just left that out too, or there are really no discoverable errors.

If you or someone else finds a way to reproduce the issue in a fresh browser profile with no other changes, please let me know and I'll reopen the issue.

**Comment by Milo123459** [comment]
The first one wasn't really a bug report, more a question. I have given you all the details you asked for in this issue, so I'm not sure why you are closing this? I can reproduce in fresh browser profiles (just tried).

**Comment by Milo123459** [comment]
Regarding me not providing logs, there are no errors. No logs either. I did say this in the issue.
