### ISSUE TITLE
Error when using Wit.ai (TypeError)

### ISSUE THREAD

**Issue by hpfariz** [dessant/buster#406]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Chrome
* Browser version: 125.0.6422.113

**Extension**

* Extension version: 3.0.0

* User input simulation: yes

* Client app version: 3.0.0
* Client app installed successfully: yes

**Bug description**
After setting up my Wit.ai API key, a TypeError comes when using the extension.

**Logs**

Browser:
```
script.js:1 Uncaught (in promise)
TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at y (script.js:1:59667)
    at async script.js:1:61754
```

**Comment by dessant** [comment]
I cannot reproduce the issue, are you using an unmodified version installed from the Chrome Web Store, or have you edited the source code of the extension?

Does the extension show the same error when you switch back to the Wit.ai (managed) service?

**Comment by hpfariz** [comment]
When I switch back to the Wit.ai (managed) services, the extension shows no error. I tried using the Google Cloud Speech-to-Text service, and the extension also shows no errors.

I downloaded the extension right from the Chrome Web Store, and I have not edited the source code for the extension. The issue is currently still reproducible on my device.

**Comment by dessant** [comment]
Please share a site link with a reCAPTCHA widget where the error occurs.

**Comment by l-Nuril-l** [comment]
It may not be related to this issue, but captcha doesn't work with extension.
https://issues.chromium.org/issues/40927938
![image](https://github.com/dessant/buster/assets/49325887/686ee07f-0484-4934-89b3-63a011d34258)

**Comment by dessant** [comment]
@l-Nuril-l, I cannot reproduce the issue, the reCAPTCHA widget loads below the comment field after signing in. Yes, your issue is different.

There is nothing I can do with both of your issues because I cannot reproduce them, and there is a bunch of important information missing. If you want to find a way for reproducing the issue, you will have to record your steps in a new browser profile and share the steps you took, including a screen recording showing everying, from the browser you use to the error message you get in the browser console on a specific site.

**Comment by l-Nuril-l** [comment]
@dessant In my case it turns out.
Latest versions of extensions conflict with each other.
https://github.com/NopeCHALLC/nopecha-extension
https://chromewebstore.google.com/detail/nopecha-captcha-solver/dknlfmjaanfblgfdfebhijalfmhmjjjo

**Comment by l-Nuril-l** [comment]
@dessant Could you fix the conflict? I would like to use 2 extensions as before.

**Comment by dessant** [comment]
@l-Nuril-l, see this comment for details: https://github.com/dessant/buster/issues/407#issuecomment-2159116449
