### ISSUE TITLE
What is this feature?

### ISSUE THREAD

**Issue by rustam2208** [dessant/buster#43]
**System**

* OS name: Windows
* OS version: 7
* Browser name: Chrome
* Browser version: 72

**Extension**

* Extension version: 0.5.0

* User input simulation: [e.g. yes, no]

* Client app version: [e.g. 1.0.0]
* Client app installed successfully: [e.g. yes, no]

**Bug description**

**Logs**

Browser:
```
// REPLACE WITH LOGS
```

Client app:
```
// REPLACE WITH LOGS
```

**Comment by rustam2208** [comment]
What kind of function "Simulate user input" , why, and how to turn it on?

**Comment by dessant** [comment]
User input simulation will move your mouse, you can turn it on from the extension's options page, then follow the instructions to download and install the program that makes the feature possible.

**Comment by picolens** [comment]
Firstly thank you so much for an amazing piece of free software. I'm really grateful and glad you chose to share it with the world.

On a side note, this "simulate" feature sounds really interesting. However, like the OP, I'm finding it hard to find out what it really means. I've read all the wikis and readme's in main repo and client and came up empty handed when looking for a more detailed explanation?

Why would a user want this option practically speaking? Does it help prevent fingerprinting? Is it because it increases success rate? How did it come about that you chose to implement this? It's quite obviously there for a greater reason than just that which is self evident, viz moving the mouse.

Anyway, hope that's not too many questions and don't mean to be a burden. Perhaps another more informed user can jump in here.

**Comment by dessant** [comment]
The client app can send trusted input events, which cannot be done from the extension, so it makes the user input look a bit more natural.

**Comment by picolens** [comment]
Thank you. Sounds like a nice feature
