### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by ziomixshot** [dessant/buster#51]
I've seen that solver doesn't work. I looked into console and here's the bug log:
script.js:1 Uncaught (in promise) Error: API response: 400, Bad Request
    at E (script.js:1)
    at www.google.com/recaptcha/api2/async chrome-extension:/mpbjkejclgfgadiemmefgebjfooflfhl/src/solve/script.js:1

My OS: Windows 10
Browser: chrome

**Comment by SebTota** [comment]
I also just ran into the same problem. My guess is that you are using a non demo version of a speech-to-text api. I found that going to the Demo of Wit Speech API makes it work, at-least until we figure out what the error is.

**Comment by narcolepticinsomniac** [comment]
I'm getting the same error starting today.

**Comment by dessant** [comment]
As @SebTota said, switch to the Wit Speech API (demo) speech service from the extension's options.

**Comment by narcolepticinsomniac** [comment]
My bad, I didn't even realize there were options. I thought you were discussing implementing an alternative. That's good news, thanks.

**Comment by ziomixshot** [comment]
Yeah, it helped. To fix it click the solver icon > manage extensions > extensions options > there switch to Wit Speech API.
It's for everyone who has the same bug. ^^
Thanks everyone for help!

**Comment by dessant** [comment]
Let's keep this open until the issue is fixed.

**Comment by dessant** [comment]
Buster 0.5.2 was published, the Chrome and Opera listings may take a couple of days to be approved and published.

The default demo speech service has been removed because similar outages have happened before, the extension now uses **Wit Speech API (demo)** by default.

Those wishing to continue using Google Speech API can select the service from the extension's options and sign up for an API key at https://cloud.google.com/speech-to-text/. The service has a free tier, but it requires a credit card.

**Comment by halil1381** [comment]
The removal of the "Google Cloud Speech Demo" service upset me. :( I think he was working better than Wit Speech. I think it was working better than "Wit Speech Service".

**Comment by dessant** [comment]
@halil1381, the API has stopped working entirely in the past few days, there is no reason to keep it around.

**Comment by halil1381** [comment]
I'm using Chrome in version 0.5.1. Not implemented here yet. The Google Cloud Speech Demo service works fine. 

Sometimes it wasn't working. If it doesn't work, I'm going to the Wit Speech API (demo) service. Would be nice to stay as an extra option. 

(Maybe it can switch to Wit Service automatically if something goes wrong with the Google service)

((Sorry for the bad english))

**Comment by SebTota** [comment]
I highly recommend just making a wit speech api account. You can sign in with your GutHub account and be ready in minutes. There is a list of all the audio you sent it and what the AI translated it to. If it was wrong you can change it and hopefully it will work better next time.

**Comment by dessant** [comment]
Ok, I'm going to start hiding comments that have no substance or contain misinformation. I have tested the removed API moments ago and it returns this status code: 400. The API simply no longer works because it has started requiring a solved captcha for every call.

**Comment by dessant** [comment]
@SebTota, you can sign up for a Wit account if you want to, but that is not required for the extension to work, the Wit Speech API (demo) speech service does not need an user supplied API key.

**Comment by halil1381** [comment]
I made a video to prove that the service was working. You can check.
https://imgur.com/EaMxTPx

The final decision is yours. You're the boss ;)

**Comment by dessant** [comment]
It's possible that they haven't yet deployed the API restrictions to all languages or request sources, but it is bound to happen. On my part it no longer works, and the reviews on the Chrome Web Store from the past few days are all complaining about the extension no longer working.

**Comment by dessant** [comment]
@halil1381, if you opt to load challenges in English from the extension's options, the Wit Speech API (demo) speech service should have mostly the same success rate.

Sorry if I came off a bit harsh in my previous post, I've just been getting a lot of low quality messages both in public and private in the last few months, and I must start filtering stuff out heavily because it takes away a good chunk of my free time.

It's best to start with clear and reproducible details whenever there is something to discuss in the future, so we don't waste a bunch of time until we get on the same page about an issue.

**Comment by throwaway666** [comment]
i've had this issue for weeks but when i try to install the program i'm told to download i get a new tab saying "something has gone wrong". doesn't matter if i pick the Wit demo or use API.

**Comment by dessant** [comment]
The new version is now live everywhere.
