### ISSUE TITLE
Error installing client: setup must be run without administrative rights

### ISSUE THREAD

**Issue by Edszx** [dessant/buster#89]
**System**

* OS name: Windows
* OS version: 10, Build 1809.
* Browser name: Waterfox
* Browser version: 56.2.10

**Extension**

* Extension version: 0.6.0

* User input simulation: Yes

* Client app version: 0.2.0
* Client app installed successfully: No

**Bug description**

Can't install the client, says it needs to run without admin rights, and yes, i tried running the browser and setup with and without admin rights and it doesn't solve it.

**Logs**

Browser:
```
Error: setup must be run without administrative rights
```

Client app:
```
2019/06/06 14:12:46.487629 Starting setup (version: 0.2.0)
2019/06/06 14:12:47.092660 Loading setup page
2019/06/06 14:12:48.036884 Getting install location
```

**Comment by dessant** [comment]
Is UAC enabled? A permission prompt should appear when you try to install Waterfox for example.

**Comment by Edszx** [comment]
> 
> 
> Is UAC enabled? A permission prompt should appear when you try to install Waterfox for example.

No UAC is completely disabled in my windows 10 installation, since opening this issue, i had seen a thread that says that the client app doesn't install if windows has UAC disabled, i really don't get why the installation clings to UAC this way, i use a lot of alpha and beta state software, and even then this is the first time i see this behavior, a program that plainly refuses to install because i have UAC disabled, i know that makes every program to run as admin by default, but i'm even running the browser and client app installer with a CLI command to make them explicitly run without admin rights.

**Comment by dessant** [comment]
Installation using root is not allowed because it complicates development and user support. Setting and updating the correct registry keys is messier on Windows, and changing users could cause issues during automatic updates. The client app may be installed as root on Linux, and then ran as a different user, which could break the app after an update.

All these issues will fall upon me to debug, and I truly lack the time for that. If you would like to make a pull request that allows installation as admin/root, and takes care of most edge cases, I'd be happy to review and merge it.

Alternatively, you can enable UAC during installation and updates.

**Comment by Edszx** [comment]
Oh well, fair enough, at the end of the day it's you program, so you have the last word, thanks for your time!
